### ISSUE TITLE
once an automation run is complete, i cannot use the same machine to submit another run

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#375]
- when a run is complete, i cannot deploy another run using the same machine.  I have to restart the run manager.

- when a run starts, the machine still shows online.  It should show "in progress" in available test pc

- re-run gives error message

**Comment by Taitalus** [comment]
please tell @minar09  fix the SendEmail function the MainDriver.py other wise the function returns a error. 
@riz-hossain  the rerun is okay. I fixed that earlier.it's working on mine though. I will see that also.

**Comment by riz-hossain** [comment]
But it should be handled still. Run manager should still continue even if email features fails. The availability status on the deployment page must be updated accordingly.  Also that page should be sorted by available machine being at the top. When I try to re-run it shows error on the page. Re-run will probably work once you fix the run manager bug. @minar what is the main issue with email here?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Sunday, February 8, 2015 12:34 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] once an automation run is complete, i cannot use the same machine to submit another run (#375)please tell @minar09  fix the SendEmail function the MainDriver.py other wise the function returns a error. 
@riz-hossain  the rerun is okay. I fixed that earlier.it's working on mine though. I will see that also.

—Reply to this email directly or view it on GitHub.

**Comment by minar09** [comment]
Email was kept commented out because of some error in run(I dont know
though coz i didn't face any.) Still that email function giving error?? I
haven't looked up to it since i implemented that.

On Sun, Feb 8, 2015 at 11:40 AM, Riz Hossain <notifications@github.com>
wrote:

> But it should be handled still. Run manager should still continue even if
> email features fails. The availability status on the deployment page must
> be updated accordingly.  Also that page should be sorted by available
> machine being at the top. When I try to re-run it shows error on the page.
> Re-run will probably work once you fix the run manager bug. @minar what is
> the main issue with email here?
> Sent from my BlackBerry 10 smartphone on the TELUS network. From: Raju
> Ahmed ShetuSent: Sunday, February 8, 2015 12:34 AMTo:
> AutomationSolutionz/Framework_0.1Reply To:
> AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re:
> [Framework_0.1] once an automation run is complete, i cannot use the same
> machine to submit another run (#375)please tell @minar09 fix the SendEmail
> function the MainDriver.py other wise the function returns a error.
> @riz-hossain the rerun is okay. I fixed that earlier.it's working on mine
> though. I will see that also.
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/375#issuecomment-73398071>
> .
>



-- 
Matiur Rahman Minar
Programmer
Automation Solutionz
1212 Countrystone Drive,
Kitchener, N2N 3R4.

**Comment by Taitalus** [comment]
It is fixed . you can close it now.

**Comment by riz-hossain** [comment]
Okay. Add the done tag to it.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Sunday, February 8, 2015 10:50 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] once an automation run is complete, i cannot use the same machine to submit another run (#375)It is fixed . you can close it now. 

—Reply to this email directly or view it on GitHub.
